
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 26 03:29:18 CET 2007
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLAIN_TEXT = 16;
  public static final int GRAFFACHIUSA = 3;
  public static final int ATOMO = 14;
  public static final int ATTRIBUZIONE = 10;
  public static final int EOF = 0;
  public static final int GRAFFAPERTA = 2;
  public static final int MY_TYPE = 13;
  public static final int PT = 8;
  public static final int NUMERO = 7;
  public static final int TYPE = 12;
  public static final int error = 1;
  public static final int VIR = 9;
  public static final int QUADRAPERTA = 4;
  public static final int PTVIR = 15;
  public static final int KEYWORD = 11;
  public static final int OR = 6;
  public static final int QUADRACHIUSA = 5;
}

